projects:
  littlebits1:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: zfmpmynu4fg6np32kgjiegu7mi
      endpoints:
        prod: >-
          https://22o6adacr5bmrcvnat3tnq7foi.appsync-api.us-east-1.amazonaws.com/graphql
